//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Player Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CycloneControls"",
            ""id"": ""786a4a70-d1e5-4781-8ae9-4069035cf41b"",
            ""actions"": [
                {
                    ""name"": ""Camera Aim"",
                    ""type"": ""Button"",
                    ""id"": ""65e20e0e-9438-470a-933b-419ae9902da1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c34b25d-9c50-48a5-b3f8-372edc91d9df"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CycloneControls
        m_CycloneControls = asset.FindActionMap("CycloneControls", throwIfNotFound: true);
        m_CycloneControls_CameraAim = m_CycloneControls.FindAction("Camera Aim", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CycloneControls
    private readonly InputActionMap m_CycloneControls;
    private List<ICycloneControlsActions> m_CycloneControlsActionsCallbackInterfaces = new List<ICycloneControlsActions>();
    private readonly InputAction m_CycloneControls_CameraAim;
    public struct CycloneControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CycloneControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraAim => m_Wrapper.m_CycloneControls_CameraAim;
        public InputActionMap Get() { return m_Wrapper.m_CycloneControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CycloneControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICycloneControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CycloneControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CycloneControlsActionsCallbackInterfaces.Add(instance);
            @CameraAim.started += instance.OnCameraAim;
            @CameraAim.performed += instance.OnCameraAim;
            @CameraAim.canceled += instance.OnCameraAim;
        }

        private void UnregisterCallbacks(ICycloneControlsActions instance)
        {
            @CameraAim.started -= instance.OnCameraAim;
            @CameraAim.performed -= instance.OnCameraAim;
            @CameraAim.canceled -= instance.OnCameraAim;
        }

        public void RemoveCallbacks(ICycloneControlsActions instance)
        {
            if (m_Wrapper.m_CycloneControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICycloneControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CycloneControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CycloneControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CycloneControlsActions @CycloneControls => new CycloneControlsActions(this);
    public interface ICycloneControlsActions
    {
        void OnCameraAim(InputAction.CallbackContext context);
    }
}
